language: ruby
dist: trusty
rvm:
  - 2.4.2

script:
  - cd api
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec

addons:
  postgresql: 9.6